#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MODEL_DIR="${DIR}/.."
[ -z "${OUTPUT_FILE}" ] && OUTPUT_FILE="${MODEL_DIR}/model.sdf"

config=""
for file in "${MODEL_DIR}/config/common.yaml" "${MODEL_DIR}/config/sim.yaml" "${MODEL_DIR}/config/ign.yaml"; do
  config="${config} $("${DIR}/yaml_to_xacro_args" "$file")"
done

sdf8_version="$(ign sdf --versions | grep '^8')" || true
[ -z "$sdf8_version" ] && echo "libsdformat8 not found. It is required to update this robot's SDF. Please install libsdformat8-dev and try again." >&2 && exit 1
echo "Found libsdformat ${sdf8_version}" >&2

echo -e "Rendering Ignition Gazebo SDF of $(basename "$(realpath "$MODEL_DIR")") with the following Xacro arguments:\n${config}" "$@" >&2
rosrun xacro xacro "${MODEL_DIR}/urdf/robot.xacro" ${config} "$@" > "${OUTPUT_FILE}.urdf"
ign sdf --force-version "$sdf8_version" -p "${OUTPUT_FILE}.urdf" | "${DIR}/high_precision_constants.py" - > "${OUTPUT_FILE}"

"${DIR}/clean_sdf" "${OUTPUT_FILE}"
# fix resource paths
sed -i -e 's#model://ctu_cras_norlab_husky_sensor_config_3/##g' "${OUTPUT_FILE}"
sed -i -e 's#model://ctu_cras_norlab_husky_sensor_config_1/#https://fuel.ignitionrobotics.org/1.0/OpenRobotics/models/CTU_CRAS_NORLAB_HUSKY_SENSOR_CONFIG_1/tip/files/#g' "${OUTPUT_FILE}"