left_front:
  - front_left_hip_x
  - front_left_hip_y
  - front_left_knee
  - front_left_foot

right_front:
  - front_right_hip_x
  - front_right_hip_y
  - front_right_knee
  - front_right_foot

left_hind:
  - rear_left_hip_x
  - rear_left_hip_y
  - rear_left_knee
  - rear_left_foot

right_hind:
  - rear_right_hip_x
  - rear_right_hip_y
  - rear_right_knee
  - rear_right_foot