"":
  joint_group_position_controller:
      gains:
        front_left_hip_x  : {p: 280, i: 0.3, d: 7.0}
        front_left_hip_y  : {p: 280, i: 0.3, d: 7.0}
        front_left_knee   : {p: 280, i: 0.3, d: 7.0}
        front_right_hip_x : {p: 280, i: 0.3, d: 7.0}
        front_right_hip_y : {p: 280, i: 0.3, d: 7.0}
        front_right_knee  : {p: 280, i: 0.3, d: 7.0}
        rear_left_hip_x   : {p: 280, i: 0.3, d: 7.0}
        rear_left_hip_y   : {p: 280, i: 0.3, d: 7.0}
        rear_left_knee    : {p: 280, i: 0.3, d: 7.0}
        rear_right_hip_x  : {p: 280, i: 0.3, d: 7.0}
        rear_right_hip_y  : {p: 280, i: 0.3, d: 7.0}
        rear_right_knee   : {p: 280, i: 0.3, d: 7.0}