#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MODEL_DIR="${DIR}/.."
SC1_MODEL_DIR="${MODEL_DIR}/../ctu_cras_norlab_absolem_sensor_config_1"
BASE_MODEL_DIR="${MODEL_DIR}/../ctu_cras_norlab_absolem_sensor_config_6"
[ -z "${OUTPUT_FILE}" ] && OUTPUT_FILE="${MODEL_DIR}/model.sdf"

# load local modifications of configuration and pass them to update_robot_sdf of sensor config 6
config=""
for file in "${MODEL_DIR}/config/common.yaml" "${MODEL_DIR}/config/sdf.yaml"; do
  [ -f "$file" ] && config="${config} $("${SC1_MODEL_DIR}/scripts/yaml_to_xacro_args" "$file")"
done

OUTPUT_FILE="$OUTPUT_FILE" "${BASE_MODEL_DIR}/scripts/update_robot_sdf" $config "$@"