#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MODEL_DIR="${DIR}/.."
BASE_MODEL_DIR="${MODEL_DIR}/../bosdyn_spot"

# load local modifications of configuration and apply them over the config from bosdyn_spot

config=""
for file in "${BASE_MODEL_DIR}/config/model/common.yaml" "${BASE_MODEL_DIR}/config/model/urdf.yaml" "${MODEL_DIR}/config/model/common.yaml" "${MODEL_DIR}/config/model/urdf.yaml"; do
  [ -f "$file" ] && config="${config} $("${BASE_MODEL_DIR}/scripts/yaml_to_xacro_args" "$file")"
done

echo -e "Rendering URDF of $(basename "$(realpath "$MODEL_DIR")") with the following Xacro arguments:\n${config}" "$@" >&2
# we replace bosdyn_spot meshes with meshes from this sensor config so that we get the blue body color
urdf="$(rosrun xacro xacro "${MODEL_DIR}/urdf/spot.urdf.xacro" ${config} "$@")"
urdf="$(echo "$urdf" | sed 's#package://bosdyn_spot/\([^>]*\.dae\)#package://marble_spot_sensor_config_1/\1#g')"
echo "$urdf"
