# This message contains competition statistics

subt_ros/Robot[] robots
# subt_ros/Marsupial[] marsupials
int32 artifacts_found
int32 robot_count
int32 unique_robot_count
int32 sim_time
int32 real_time
int32 artifact_report_count
int32 duplicate_report_count
string closest_artifact_report_name
string closest_artifact_report_type
geometry_msgs/Vector3 closest_artifact_report_true_pos
geometry_msgs/Vector3 closest_artifact_report_reported_pos
float64 closest_artifact_report_distance
string first_artifact_report
string last_artifact_report
# float64 mean_time_between_successful_artifact_reports
# float64 greatest_distance_traveled
# float64 greatest_distance_traveled_robot
# float64 greatest_euclidean_distance_from_start
# float64 greatest_euclidean_distance_from_start_robot
# float64 total_distance_traveled
# float64 greatest_max_vel
# float64 greatest_max_vel_robot
# float64 greatest_avg_vel
# float64 greatest_avg_vel_robot
# float64 greatest_elevation_gain
# float64 greatest_elevation_gain_robot
# float64 greatest_elevation_loss
# float64 greatest_elevation_loss_robot
# float64 total_elevation_gain
# float64 total_elevation_loss
# float64 max_elevation_reached
# float64 max_elevation_reached_robot
# float64 min_elevation_reached
# float64 min_elevation_reached_robot
# float64 min_elevation_reached_robot
