base: body  # this should not have the namespace, it is added in state_estimation
left_front:
  - $(arg name)/front_left_hip
  - $(arg name)/front_left_upper_leg
  - $(arg name)/front_left_lower_leg
  - $(arg name)/front_left_ee

right_front:
  - $(arg name)/front_right_hip
  - $(arg name)/front_right_upper_leg
  - $(arg name)/front_right_lower_leg
  - $(arg name)/front_right_ee

left_hind:
  - $(arg name)/rear_left_hip
  - $(arg name)/rear_left_upper_leg
  - $(arg name)/rear_left_lower_leg
  - $(arg name)/rear_left_ee

right_hind:
  - $(arg name)/rear_right_hip
  - $(arg name)/rear_right_upper_leg
  - $(arg name)/rear_right_lower_leg
  - $(arg name)/rear_right_ee