# Artifact

uint8 TYPE_BACKPACK=0
uint8 TYPE_DUCT=1
uint8 TYPE_ELECTRICAL_BOX=2
uint8 TYPE_EXTINGUISHER=3
uint8 TYPE_PHONE=4
uint8 TYPE_RADIO=5
uint8 TYPE_TOOLBOX=6
uint8 TYPE_VALVE=7

geometry_msgs/PoseStamped pose
uint8 type
---
bool success
