#!/usr/bin/env bash
set -e

# There is a lot of ballast in the SDF file produced by ign sdf... This script
# just cleans a part of it to increase its readability.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# this is a trick to edit the file inplace without creating an explicit tempfile
# see https://backreference.org/2011/01/29/in-place-editing-of-files/
{ rm "$1"; "${DIR}/high_precision_constants.py" - > "$1"; } < "$1"

sed -i \
  -e '/<surface>/{:a;N;/<\/surface>/!ba};/<surface>\n\s*<contact>\n\s*<ode\/>\n\s*<\/contact>\n\s*<friction>\n\s*<ode\/>\n\s*<\/friction>\n\s*<\/surface>/d' \
  -e '/<contact>/{:b;N;/<\/contact>/!bb};/<contact>\n\s*<ode\/>\n\s*<\/contact>/d' \
  -e '/<pose>\(-\?0 \?\)\{6\}<\/pose>/d' \
  -e '/<scale>1 1 1<\/scale>/d' \
  -e '/<angular_velocity\/>/d' \
  -e '/<linear_acceleration\/>/d' \
  -e '/<velocity_decay\/>/d' \
  -e '/<gravity>1<\/gravity>/d' \
  -e '/<kinematic>0<\/kinematic>/d' \
  -e '/<static>0<\/static>/d' \
  "$1"