<?xml version="1.0"?>
<root xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="thermocam_mass" value="0.024" scope="global" /> <!-- https://flir.netx.net/file/asset/15754/original/attachment -->

    <xacro:macro name="boson_thermocam" params="name simulate:=1 visualize:=0">
        <!-- Thermal camera - FLIR Boson 320 20320H092 -->
        <link name="$(arg prefix)${name}">
            <visual>
                <origin xyz="0 0 ${0.021/2}" />
                <geometry>
                    <mesh filename="package://ctu_cras_norlab_absolem_sensor_config_1/meshes/flir_boson.dae" />
                </geometry>
            </visual>
            <collision>
                <origin xyz="${0.043/2 - 0.006} 0 0" />
                <geometry>
                    <box size="0.043 0.021 0.021"/>
                </geometry>
            </collision>
            <xacro:box_inertial mass="${thermocam_mass}" width="0.021" height="0.021" depth="0.043" xyz="${0.043/2 - 0.006} 0 0" />
        </link>
        <xacro:if value="${simulate}">
            <gazebo reference="$(arg prefix)${name}">
                <sensor name="thermal_camera" type="thermal_camera">
                    <pose>0.030 0 0 0 0 0</pose>
                    <always_on>1</always_on>
                    <update_rate>8.6</update_rate>
                    <visualize>${visualize}</visualize>
                    <camera name="thermal_camera">
                        <xacro:property name="hfov" value="${radians(92)}" />
                        <xacro:property name="width" value="320" />
                        <xacro:property name="height" value="256" />
                        <horizontal_fov>${hfov}</horizontal_fov>
                        <lens>
                            <intrinsics>
                                <xacro:property name="focal_length" value="${320 / (2 * tan(radians(92) / 2))}" />
                                <fx>${focal_length}</fx>
                                <fy>${focal_length}</fy>
                                <cx>${(width + 1) / 2.0}</cx>
                                <cy>${(height + 1) / 2.0}</cy>
                                <s>0</s>
                            </intrinsics>
                        </lens>
                        <image>
                            <width>${width}</width>
                            <height>${height}</height>
                            <format>L8</format>
                        </image>
                        <clip>
                            <near>0.6</near>
                            <far>50</far>
                        </clip>
                    </camera>
                    <plugin filename="ignition-gazebo-thermal-sensor-system" name="ignition::gazebo::systems::ThermalSensor">
                        <min_temp>253.15</min_temp>
                        <max_temp>673.15</max_temp>
                        <resolution>1.6</resolution>
                    </plugin>
                </sensor>
            </gazebo>
        </xacro:if>
    </xacro:macro>
</root>
