# Export Ignition environment variables

@[if INSTALLSPACE]@
export IGN_LAUNCH_CONFIG_PATH=@(CMAKE_INSTALL_PREFIX)/@(CATKIN_PACKAGE_SHARE_DESTINATION)/launch
export IGN_GAZEBO_RESOURCE_PATH=@(CMAKE_INSTALL_PREFIX)/@(CATKIN_PACKAGE_SHARE_DESTINATION)/worlds:${IGN_GAZEBO_RESOURCE_PATH}
@[else]@
export IGN_LAUNCH_CONFIG_PATH=@(CMAKE_CURRENT_SOURCE_DIR)/launch
export IGN_GAZEBO_RESOURCE_PATH=@(CMAKE_CURRENT_SOURCE_DIR)/worlds:${IGN_GAZEBO_RESOURCE_PATH}
@[end if]@
