leg_kp: 1e+7
leg_kd: 100.0
leg_mu1: 0.8
leg_mu2: 0.8
# leg_fdir1: '0 0 1'

max_knee_effort: 80
max_knee_velocity: 15
max_hip_x_effort: 80
max_hip_x_velocity: 15
max_hip_y_effort: 80
max_hip_y_velocity: 15