#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MODEL_DIR="${DIR}/.."

source "${MODEL_DIR}/config/common.sh"
source "${MODEL_DIR}/config/sdf.sh"

sdf8_version="$(ign sdf --versions | grep '^8')" || true
[ -z "$sdf8_version" ] && echo "libsdformat8 not found. It is required to update this robot's SDF. Please install libsdformat8-dev and try again." >&2 && exit 1
echo "Found libsdformat ${sdf8_version}" >&2

rosrun xacro xacro "${MODEL_DIR}/urdf/nifti_robot.xacro" ${config} > "${MODEL_DIR}/nifti_robot.sdf.urdf"
ign sdf --force-version "$sdf8_version" -p "${MODEL_DIR}/nifti_robot.sdf.urdf" | "${DIR}/high_precision_constants.py" - > "${MODEL_DIR}/model.sdf"
sed -i -e 's#model://ctu_cras_norlab_absolem_sensor_config_1/##g' \
  -e '/<surface>/{:a;N;/<\/surface>/!ba};/<surface>\n\s*<contact>\n\s*<ode\/>\n\s*<\/contact>\n\s*<friction>\n\s*<ode\/>\n\s*<\/friction>\n\s*<\/surface>/d' \
  -e '/<pose>\(-\?0 \?\)\{6\}<\/pose>/d' \
  -e '/<scale>1 1 1<\/scale>/d' \
  -e '/<angular_velocity\/>/d' \
  -e '/<linear_acceleration\/>/d' \
  -e '/<velocity_decay\/>/d' \
  -e '/<gravity>1<\/gravity>/d' \
  -e '/<kinematic>0<\/kinematic>/d' \
  -e '/<static>0<\/static>/d' "${MODEL_DIR}/model.sdf"
sed -i '/<contact>/{:a;N;/<\/contact>/!ba};/<contact>\n\s*<ode\/>\n\s*<\/contact>/d' "${MODEL_DIR}/model.sdf"