#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MODEL_DIR="${DIR}/.."
BASE_MODEL_DIR="${MODEL_DIR}/../ctu_cras_norlab_marv_sensor_config_1"

# load local modifications of configuration and pass them to print_robot_urdf of sensor config 1

config=""
for file in "${MODEL_DIR}/config/common.yaml" "${MODEL_DIR}/config/urdf.yaml"; do
  [ -f "$file" ] && config="${config} $("${BASE_MODEL_DIR}/scripts/yaml_to_xacro_args" "$file")"
done

"${BASE_MODEL_DIR}/scripts/print_robot_urdf" $config "$@"