#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MODEL_DIR="${DIR}/.."
BOSDYN_MODEL_DIR="${MODEL_DIR}/../bosdyn_spot"
BASE_MODEL_DIR="${MODEL_DIR}/../ctu_cras_norlab_spot_sensor_config_1"

# load local modifications of configuration and apply them over the config from ctu_cras_norlab_spot_sensor_config_1

config=""
for file in "${MODEL_DIR}/config/model/common.yaml" "${MODEL_DIR}/config/model/urdf.yaml"; do
  [ -f "$file" ] && config="${config} $("${BOSDYN_MODEL_DIR}/scripts/yaml_to_xacro_args" "$file")"
done

"${BASE_MODEL_DIR}/scripts/print_robot_urdf" $config "$@"